export default {
    state: {
        users: [
            {
                id: 1,
                name: "Tim",
                surname: "Adler",
                userRole: [
                    {name: "Card Management", systemsAplications: ".CARD"},
                    {name: "DIM Management", systemsAplications: "#Identity"},
                ],
                isActive: true,
                information: 'Information',
                email: 'Tim.Adler@Musterag.de',
                userName: 'AdlerT',
                userCreater: '19.07.2022 16:20',
            },
            {
                id: 2,
                name: "Karl",
                surname: "Bader",
                userRole: [
                    {name: "Card Management", systemsAplications: ".CARD"},
                    {name: "DIM Management", systemsAplications: "#DigitalIdentitymanagement"},
                ],
                isActive: true,
                information: 'Information',
                email: 'Karl.Bader@Mustermann.de',
                userName: 'KarlB',
                userCreater: '19.07.2022 16:17',
            },
            {
                id: 3,
                name: "Nadja",
                surname: "Doser",
                userRole: [
                    {name: "Lockingsystem Management", systemsAplications: ".VISIT"},
                    {name: "Visitor Management", systemsAplications: ".VISIT"},
                ],
                isActive: true,
                information: 'Information',
                email: 'Nadja.Diser@Mueller.de',
                userName: 'NadjaD',
                userCreater: '19.07.2022 16:22',
            },
            {
                id: 4,
                name: "Klaus",
                surname: "Eder",
                userRole: [
                    {name: "Card Manager", systemsAplications: ".CARD"},
                ],
                isActive: false,
                information: 'Information',
                email: 'Klaus.Eder@company1.de',
                userName: 'KlausE',
                userCreater: '19.07.2022 16:28',
            },
            {
                id: 5,
                name: "Hans",
                surname: "Eller",
                userRole: [
                    {name: "Access Manager", systemsAplications: ".ACCESS"},
                    {name: "DIM Management", systemsAplications: "#DigitalIdentitymanagement"},
                    {name: "EXTERNAL Manager", systemsAplications: ".EXTERNAL"},
                ],
                isActive: false,
                information: 'Information',
                email: 'Hans.Eller@muster.de',
                userName: 'HansE',
                userCreater: '21.07.2022 14:48',
            },
            {
                id: 6,
                name: '',
                surname: '',
                userRole: [
                    {name: "Card Management", systemsAplications: ".CARD"},
                    {name: "DIM Management", systemsAplications: "#Identity"},
                ],
                isActive: true,
                information: 'Information',
                email: 'a.goeller@gis-GmbH.de',
                userName: '',
                userCreater: '21.07.2022 19:04',
            },
            {
                id: 7,
                name: "Tom",
                surname: "Holland",
                userRole: [
                    {name: "Lockingsystem Management", systemsAplications: ".VISIT"},
                    {name: "Visitor Management", systemsAplications: ".VISIT"},
                ],
                isActive: true,
                information: 'Information',
                email: 'Tom.Holland@Muster.de',
                userName: 'TomH',
                userCreater: '02.08.2022 10:36',
            },
            {
                id: 8,
                name: "Aleks",
                surname: "Olson",
                userRole: [
                    {name: "Access Manager", systemsAplications: ".ACCESS"},
                    {name: "DIM Management", systemsAplications: "#DigitalIdentitymanagement"},
                ],
                isActive: true,
                information: 'Information',
                email: 'Aleks.Olson@Muster.de',
                userName: 'AleksO',
                userCreater: '03.08.2022 13:14',
            },
        ],
    },
    mutations: {},
    getters: {
        getAllUsers(state) {
            return state.users;
        },
    },
    actions: {}
}